//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rozvrh {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Prima {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Prima() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rozvrh.Prima", typeof(Prima).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rozvrh - расписание.
        /// </summary>
        public static string appHeader {
            get {
                return ResourceManager.GetString("appHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сменить язык.
        /// </summary>
        public static string changelang {
            get {
                return ResourceManager.GetString("changelang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверьте ввод.
        /// </summary>
        public static string checklesson {
            get {
                return ResourceManager.GetString("checklesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалено..
        /// </summary>
        public static string deleted {
            get {
                return ResourceManager.GetString("deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cброс настроек.
        /// </summary>
        public static string deletesettings {
            get {
                return ResourceManager.GetString("deletesettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово, I&apos;ve ملأت.
        /// </summary>
        public static string enterlesson {
            get {
                return ResourceManager.GetString("enterlesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to п&apos;ятниця.
        /// </summary>
        public static string friday {
            get {
                return ResourceManager.GetString("friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Урок.
        /// </summary>
        public static string lesson {
            get {
                return ResourceManager.GetString("lesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to урок..
        /// </summary>
        public static string lesson1 {
            get {
                return ResourceManager.GetString("lesson1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to урока..
        /// </summary>
        public static string lesson24 {
            get {
                return ResourceManager.GetString("lesson24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to уроков..
        /// </summary>
        public static string lessonoth {
            get {
                return ResourceManager.GetString("lessonoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Энтер зэ лэссон тайтл.
        /// </summary>
        public static string lessontitle {
            get {
                return ResourceManager.GetString("lessontitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to понедiлок.
        /// </summary>
        public static string monday {
            get {
                return ResourceManager.GetString("monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалено..
        /// </summary>
        public static string notdeleted {
            get {
                return ResourceManager.GetString("notdeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы точно хотите сбросить все настройки? Их нельзя будет вернуть!.
        /// </summary>
        public static string sbrosclickbody {
            get {
                return ResourceManager.GetString("sbrosclickbody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВНИМАНИЕ.
        /// </summary>
        public static string sbrosclickheader {
            get {
                return ResourceManager.GetString("sbrosclickheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to параметри.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to четвер.
        /// </summary>
        public static string thursday {
            get {
                return ResourceManager.GetString("thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сегодня .
        /// </summary>
        public static string today {
            get {
                return ResourceManager.GetString("today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to уникальное трио - название чешское, заголовки украинские, ну а этот текст... русский!.
        /// </summary>
        public static string trio {
            get {
                return ResourceManager.GetString("trio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вівторок.
        /// </summary>
        public static string tuesday {
            get {
                return ResourceManager.GetString("tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to середа.
        /// </summary>
        public static string wednesday {
            get {
                return ResourceManager.GetString("wednesday", resourceCulture);
            }
        }
    }
}
